export const CREATE_MERCHANT = "CREATE_MERCHANT";
export const LOAD_TRANSACTIONS_SUCCESS = "LOAD_TRANSACTIONS_SUCCESS";
export const LOAD_MERCHANTS_SUCCESS = "LOAD_MERCHANTS_SUCCESS";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";